# \u5E94\u7528\u540D\u79F0
spring.application.name=admin
server.port=28100


spring.cloud.nacos.server-addr=localhost:8848
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
spring.cloud.nacos.discovery.namespace=dev

spring.security.user.name=admin
spring.security.user.password=admin123

spring.cloud.nacos.discovery.metadata.user.name=admin
spring.cloud.nacos.discovery.metadata.user.password=admin123


