<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.bbwres</groupId>
        <artifactId>biscuit-guide</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>biscuit-scheduler</artifactId>
    <name>biscuit-scheduler</name>
    <description>定时任务</description>


    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.bbwres</groupId>
            <artifactId>biscuit-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.bbwres</groupId>
            <artifactId>biscuit-micrometer-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.bbwres</groupId>
            <artifactId>biscuit-scheduler-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.bbwres</groupId>
            <artifactId>biscuit-nacos-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.bbwres</groupId>
            <artifactId>biscuit-web-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.bbwres</groupId>
            <artifactId>biscuit-rpc-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
